# Generated by Django 5.1.5 on 2026-03-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Anonymous display name', max_length=50)),
                ('avatar_emoji', models.CharField(choices=[('😎', 'Cool'), ('🦊', 'Fox'), ('🐱', 'Cat'), ('🌸', 'Flower'), ('🔥', 'Fire'), ('💀', 'Skull'), ('👻', 'Ghost'), ('🎭', 'Mask'), ('🌙', 'Moon'), ('⚡', 'Lightning')], default='👻', max_length=4)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
